
version: 2

models:
    - name: dim_emp_modelex
      description: "A starter dbt model"
      columns:
          - name: EMPNO
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_emp_ex
      description: "A starter dbt model"
      columns:
          - name: EMPNO
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
